#!/bin/bash

set -exo pipefail

PLUGIN_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/.."

BUNDLE_GEMFILE=$PLUGIN_DIR/Gemfile bundle install --quiet
BUNDLE_GEMFILE=$PLUGIN_DIR/Gemfile bundle exec ruby $PLUGIN_DIR/lib/report_github_statuses.rb
